In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(arr)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [5]:
#a
sum_ =np.sum(arr)
print("Sum: ",sum_)
mean_ = np.mean(arr)
print("Mean: ",mean_)
median_ = np.median(arr)
print("Median: ",median_)
std_dev = np.std(arr)
print("Standard Devistion: ",std_dev)

Sum:  210
Mean:  10.5
Median:  10.5
Standard Devistion:  5.766281297335398


In [10]:
# for i in range(0,20):
#     if i>9:
#         print(arr[i])
five_up = (arr >= 10)
print(arr[five_up])
        

[10 11 12 13 14 15 16 17 18 19 20]


In [16]:
#2
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("arr_2d:\n ",arr_2d)
trans_=arr_2d.transpose()
print("arr_2d trans:\n ",trans_)
row_sum =np.sum(arr_2d,axis=1)
print("row_sum: ",row_sum)
column_sum =np.sum(arr_2d,axis=0)
print("column_sum: ",column_sum)

arr_2d:
  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr_2d trans:
  [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
row_sum:  [10 26 42 58]
column_sum:  [28 32 36 40]


In [21]:
arr_2d_a = np.array([[1,2,3],[4,5,6],[6,8,9]])
arr_2d_b =np.array( [[12,13,16],[19,20,15],[14,5,8]])
print(arr_2d_a)
print(arr_2d_b)
add = np.add(arr_2d_a,arr_2d_b)
print("add:",add)
sub =np.subtract(arr_2d_a,arr_2d_b)
print("subtract:",sub)
mul =np.multiply(arr_2d_a,arr_2d_b)
print("multiply:",mul)

# Dot product
dot_product=np.dot(arr_2d_a,arr_2d_b)
print("Dot ptoduct: ",dot_product)


[[1 2 3]
 [4 5 6]
 [6 8 9]]
[[12 13 16]
 [19 20 15]
 [14  5  8]]
add: [[13 15 19]
 [23 25 21]
 [20 13 17]]
subtract: [[-11 -11 -13]
 [-15 -15  -9]
 [ -8   3   1]]
multiply: [[ 12  26  48]
 [ 76 100  90]
 [ 84  40  72]]
Dot ptoduct:  [[ 92  68  70]
 [227 182 187]
 [350 283 288]]


In [28]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr)
arr_1=arr.reshape(3,4)
print(arr_1)
sliced = arr_1[0:2, -2:]
print("Sliced array:\n", sliced)


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Sliced array:
 [[3 4]
 [7 8]]
